[package]
name = "transport-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
tokio = { version = "1.35", features = ["sync", "macros", "rt"] }
thiserror = "1.0"
parking_lot = "0.12"
